---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - puppet_master_server:
      value: puppet-master-server.example.com
  - puppet_ca_server:
      value: puppet-ca-server.example.com
  - puppet_db_server:
      value: puppet-db-server.example.com
