---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - idm_server:
      value: idm-server.example.com
  - idm_user:
      value: admin
  - idm_update_dns:
      value: 'true'
  - idm_config_mkhomedir:
      value: 'false'
  - idm_config_ssh:
      value: 'false'
