---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - search_by_ea:
      value: 'false'
  - object_ea_value:
      value: extensible-attr-filter-value
  - object_type:
      value: network
  - object_ea_key:
      value: extensible-attr-filter-key
  - api_version:
      value: v1.4
  - username:
      value: cloudforms-svc-acct
  - server:
      value: infoblox.example.com
