---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - meth1:
      value: vm_name
  - meth2:
      value: service_name
